window.takeoffExercise003 = {
    exerciseId: "takeoff-practice-003",
    title: "Takeoff Practice 003",
    status: "APPROVED DRAWING",
    drawing: {
        asset: "../../Takeoff Drawings/ChatGPT Image Aug 24, 2026, 03_13_27 PM.png",
        sourceDocument: "ChatGPT Image Aug 24, 2026, 03_13_27 PM.png",
        drawingTitle: "FIRE ALARM PLAN - LEVEL 1",
        drawingNumber: "FA-1.1",
        project: "PRAIRIE MEDICAL CLINIC - LEVEL 1",
        pages: 1
    },
    key: [
        { symbol: "FACP", description: "Fire Alarm Control Panel", color: "DARK BLUE" },
        { symbol: "FAA", description: "Fire Alarm Annunciator", color: "DARK BLUE" },
        { symbol: "Circle", description: "Smoke Detector", color: "RED" },
        { symbol: "Circle", description: "Rate of Rise Heat Detector", color: "LIGHT BLUE" },
        { symbol: "Square", description: "Test Station", color: "ORANGE" },
        { symbol: "Triangle", description: "Duct Smoke Detector", color: "ORANGE" },
        { symbol: "SS", description: "Wall Speaker / Strobe", color: "YELLOW" },
        { symbol: "HS", description: "Wall Horn / Strobe", color: "YELLOW" },
        { symbol: "P", description: "Manual Pull Station", color: "GREEN" },
        { symbol: "R", description: "Control Relay (CR)", color: "PINK" },
        { symbol: "WF", description: "Waterflow Switch", color: "PINK" },
        { symbol: "DH", description: "Door Holder", color: "PINK" },
        { symbol: "T", description: "Tamper Switch", color: "PINK" }
    ],
    notes: [
        "Devices are shown diagrammatically. Refer to reflected ceiling plans for exact locations and mounting heights.",
        "All notification appliances are wall mounted at 80\" AFF unless otherwise noted.",
        "Duct smoke detectors are installed in the return air ducts. See mechanical drawings.",
        "Door holders release upon alarm.",
        "Elevators recall to level 1 upon alarm.",
        "The FACP is located in the Fire Room 125.",
        "The FAA is located at the Nurse Station 110.",
        "Coordinate all device locations with architectural, mechanical and electrical drawings."
    ],
    products: [
        { id: "facp", whatIsIt: "FACP", color: "DARK BLUE" },
        { id: "faa", whatIsIt: "FAA", color: "DARK BLUE" },
        { id: "smokes", whatIsIt: "Smokes", color: "RED" },
        { id: "ror-heats", whatIsIt: "R of R Heats", color: "LIGHT BLUE" },
        { id: "test-stations", whatIsIt: "Test Stations", color: "ORANGE" },
        { id: "duct-smokes", whatIsIt: "Duct Smokes", color: "ORANGE" },
        { id: "wall-speaker-strobes", whatIsIt: "Wall Speaker/Strobes", color: "YELLOW" },
        { id: "wall-horn-strobes", whatIsIt: "Wall Horn/Strobes", color: "YELLOW" },
        { id: "pulls", whatIsIt: "Pulls", color: "GREEN" },
        { id: "crs", whatIsIt: "CR's", color: "PINK" },
        { id: "waterflow", whatIsIt: "Waterflow", color: "PINK" },
        { id: "door-holders", whatIsIt: "Door Holders", color: "PINK" },
        { id: "tamper", whatIsIt: "Tamper", color: "PINK" }
    ],
    symbols: [],
    partNumbers: [],
    colors: [],
    locations: [
        { id: "ex003-facp-001", productId: "facp", type: "FACP", color: "DARK BLUE", x: 0.299, y: 0.806, width: 0.035, height: 0.026, room: "BREAK ROOM 125 / FIRE ROOM", drawingReference: "FA-1.1" },
        { id: "ex003-faa-001", productId: "faa", type: "FAA", color: "DARK BLUE", x: 0.379, y: 0.409, width: 0.032, height: 0.026, room: "NURSE STATION 110", drawingReference: "FA-1.1" },
        { id: "ex003-dh-001", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.303, y: 0.429, width: 0.025, height: 0.025, room: "CONSULT 109", drawingReference: "FA-1.1" },
        { id: "ex003-dh-002", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.314, y: 0.209, width: 0.025, height: 0.025, room: "EXAM 3 104", drawingReference: "FA-1.1" },
        { id: "ex003-dh-003", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.657, y: 0.233, width: 0.025, height: 0.025, room: "OFFICE 108", drawingReference: "FA-1.1" },
        { id: "ex003-wf-001", productId: "waterflow", type: "Waterflow", color: "PINK", x: 0.069, y: 0.475, width: 0.03, height: 0.025, room: "WAITING 114 / WEST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-tamper-001", productId: "tamper", type: "Tamper", color: "PINK", x: 0.251, y: 0.156, width: 0.025, height: 0.025, room: "TOP CORRIDOR / GRID 1-2", drawingReference: "FA-1.1" },
        { id: "ex003-tamper-002", productId: "tamper", type: "Tamper", color: "PINK", x: 0.56, y: 0.156, width: 0.025, height: 0.025, room: "TOP CORRIDOR / GRID 6-7", drawingReference: "FA-1.1" },
        { id: "ex003-tamper-003", productId: "tamper", type: "Tamper", color: "PINK", x: 0.686, y: 0.713, width: 0.025, height: 0.025, room: "STAIR 1", drawingReference: "FA-1.1" },
        { id: "ex003-cr-001", productId: "crs", type: "CR's", color: "PINK", x: 0.69, y: 0.793, width: 0.025, height: 0.025, room: "STAIR 1 / MECHANICAL 127", drawingReference: "FA-1.1" },
        { id: "ex003-cr-002", productId: "crs", type: "CR's", color: "PINK", x: 0.715, y: 0.285, width: 0.025, height: 0.025, room: "STAIR 2", drawingReference: "FA-1.1" },
        { id: "ex003-cr-003", productId: "crs", type: "CR's", color: "PINK", x: 0.027, y: 0.884, width: 0.025, height: 0.025, room: "VESTIBULE 100", drawingReference: "FA-1.1" },
        { id: "ex003-test-001", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.423, y: 0.322, width: 0.02, height: 0.02, room: "CENTRAL CORRIDOR / GRID 4", drawingReference: "FA-1.1" },
        { id: "ex003-test-002", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.512, y: 0.312, width: 0.02, height: 0.02, room: "CENTRAL CORRIDOR / STORAGE 112", drawingReference: "FA-1.1" },
        { id: "ex003-test-003", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.406, y: 0.554, width: 0.02, height: 0.02, room: "CENTRAL CORRIDOR / IT-DATA 117", drawingReference: "FA-1.1" },
        { id: "ex003-test-004", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.451, y: 0.7, width: 0.02, height: 0.02, room: "LOWER CORRIDOR / MEN 122", drawingReference: "FA-1.1" },
        { id: "ex003-duct-001", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.542, y: 0.286, width: 0.02, height: 0.02, room: "CENTRAL CORRIDOR / RETURN AIR", drawingReference: "FA-1.1" },
        { id: "ex003-duct-002", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.467, y: 0.52, width: 0.02, height: 0.02, room: "CENTRAL CORRIDOR / RETURN AIR", drawingReference: "FA-1.1" },
        { id: "ex003-duct-003", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.542, y: 0.714, width: 0.02, height: 0.02, room: "LOWER CORRIDOR / RETURN AIR", drawingReference: "FA-1.1" },
        { id: "ex003-ss-001", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.73, y: 0.333, width: 0.028, height: 0.028, room: "OFFICE 108 / EAST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-ss-002", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.659, y: 0.535, width: 0.028, height: 0.028, room: "ULTRASOUND 119 / EAST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-ss-003", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.263, y: 0.702, width: 0.028, height: 0.028, room: "WOMEN 121 / WEST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-ss-004", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.366, y: 0.702, width: 0.028, height: 0.028, room: "MEN 122 / WEST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-ss-005", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.4, y: 0.794, width: 0.028, height: 0.028, room: "LOCKERS 126", drawingReference: "FA-1.1" },
        { id: "ex003-hs-001", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.495, y: 0.454, width: 0.028, height: 0.028, room: "X-RAY 118 / EAST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-002", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.147, y: 0.693, width: 0.028, height: 0.028, room: "CONFERENCE 124 / EAST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-003", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.248, y: 0.785, width: 0.028, height: 0.028, room: "CONFERENCE 124 / SOUTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-pull-001", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.205, y: 0.289, width: 0.028, height: 0.028, room: "TOP CORRIDOR / WEST", drawingReference: "FA-1.1" },
        { id: "ex003-pull-002", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.682, y: 0.285, width: 0.028, height: 0.028, room: "STAIR 2 / EAST", drawingReference: "FA-1.1" },
        { id: "ex003-pull-003", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.253, y: 0.528, width: 0.028, height: 0.028, room: "CENTRAL CORRIDOR / WEST", drawingReference: "FA-1.1" },
        { id: "ex003-pull-004", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.504, y: 0.527, width: 0.028, height: 0.028, room: "CENTRAL CORRIDOR / LAB", drawingReference: "FA-1.1" },
        { id: "ex003-pull-005", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.699, y: 0.527, width: 0.028, height: 0.028, room: "ULTRASOUND / PHARMACY CORRIDOR", drawingReference: "FA-1.1" },
        { id: "ex003-pull-006", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.23, y: 0.713, width: 0.028, height: 0.028, room: "LOWER CORRIDOR / WEST", drawingReference: "FA-1.1" },
        { id: "ex003-pull-007", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.505, y: 0.713, width: 0.028, height: 0.028, room: "LOWER CORRIDOR / LOCKERS", drawingReference: "FA-1.1" },
        { id: "ex003-pull-008", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.703, y: 0.713, width: 0.028, height: 0.028, room: "STAIR 1 / EAST", drawingReference: "FA-1.1" },
        { id: "ex003-pull-009", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.38, y: 0.872, width: 0.028, height: 0.028, room: "VESTIBULE 100 / ENTRY", drawingReference: "FA-1.1" }
    ],
    expectedQuantities: {
        FACP: 1,
        FAA: 1,
        "Door Holders": 3,
        Waterflow: 1,
        Tamper: 3,
        "CR's": 3,
        "Test Stations": 4,
        "Duct Smokes": 3,
        "Wall Speaker/Strobes": 5,
        "Wall Horn/Strobes": 3,
        Pulls: 9
    },
    existingDevices: [],
    excludedDevices: [],
    specialInstructions: ["Circular detector locations are intentionally not mapped where the raster does not make Smoke versus Rate of Rise unambiguous. Expected quantities cover only the QA-approved mapped regions."]
};
