window.takeoffExercise003 = {
    exerciseId: "takeoff-practice-003",
    title: "Takeoff Practice 003",
    status: "APPROVED DRAWING",
    drawing: {
        asset: "../../Takeoff Drawings/97b81900-4fe0-4767-befe-a26e76618bee.png",
        sourceDocument: "97b81900-4fe0-4767-befe-a26e76618bee.png",
        drawingTitle: "FIRE ALARM PLAN - LEVEL 1",
        drawingNumber: "FA-1.1",
        project: "BAN-KOE ACADEMY - LEVEL 3",
        pages: 1
    },
    key: [
        { symbol: "FACP", description: "Fire Alarm Control Panel", color: "DARK BLUE" },
        { symbol: "FA", description: "Fire Alarm Annunciator", color: "DARK BLUE" },
        { symbol: "S", description: "Smoke Detector", color: "RED" },
        { symbol: "H", description: "Heat Detector (Fixed Temperature)", color: "LIGHT BLUE" },
        { symbol: "R", description: "Rate-of-Rise Heat Detector (Thermal)", color: "LIGHT BLUE" },
        { symbol: "TS", description: "Test Station", color: "ORANGE" },
        { symbol: "D", description: "Duct Smoke Detector", color: "ORANGE" },
        { symbol: "HS", description: "Wall Horn / Strobe", color: "YELLOW" },
        { symbol: "SS", description: "Wall Speaker / Strobe", color: "YELLOW" },
        { symbol: "P", description: "Manual Pull Station", color: "GREEN" },
        { symbol: "CR", description: "Control Relay", color: "PINK" },
        { symbol: "WF", description: "Waterflow Switch", color: "PINK" },
        { symbol: "DH", description: "Door Holder", color: "PINK" },
        { symbol: "T", description: "Tamper Switch", color: "PINK" }
    ],
    notes: [
        "Install devices per NFPA 72.",
        "Verify all device locations with architectural drawings.",
        "Mount devices per manufacturer recommendations.",
        "Coordinate with all trades.",
        "This is a training exercise only. Device quantities and locations are used for instructional purposes."
    ],
    products: [
        { id: "facp", whatIsIt: "FACP", color: "DARK BLUE" },
        { id: "faa", whatIsIt: "FAA", color: "DARK BLUE" },
        { id: "smokes", whatIsIt: "Smokes", color: "RED" },
        { id: "heat-detectors", whatIsIt: "Heat Detectors", color: "LIGHT BLUE" },
        { id: "ror-heats", whatIsIt: "R of R Heats", color: "LIGHT BLUE" },
        { id: "test-stations", whatIsIt: "Test Stations", color: "ORANGE" },
        { id: "duct-smokes", whatIsIt: "Duct Smokes", color: "ORANGE" },
        { id: "wall-horn-strobes", whatIsIt: "Wall Horn/Strobes", color: "YELLOW" },
        { id: "wall-speaker-strobes", whatIsIt: "Wall Speaker/Strobes", color: "YELLOW" },
        { id: "pulls", whatIsIt: "Pulls", color: "GREEN" },
        { id: "crs", whatIsIt: "CR's", color: "PINK" },
        { id: "waterflow", whatIsIt: "Waterflow", color: "PINK" },
        { id: "door-holders", whatIsIt: "Door Holders", color: "PINK" },
        { id: "tamper", whatIsIt: "Tamper", color: "PINK" }
    ],
    symbols: [],
    partNumbers: [],
    colors: [],
    locations: [
        { id: "ex003-facp-001", productId: "facp", type: "FACP", color: "DARK BLUE", x: 0.029, y: 0.562, width: 0.036, height: 0.038, room: "FIRE ALARM CONTROL PANEL", drawingReference: "FA-1.1" },
        { id: "ex003-faa-001", productId: "faa", type: "FAA", color: "DARK BLUE", x: 0.029, y: 0.417, width: 0.022, height: 0.033, room: "FIRE ALARM ANNUNCIATOR", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-001", productId: "smokes", type: "Smokes", color: "RED", x: 0.090, y: 0.160, width: 0.018, height: 0.028, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-002", productId: "smokes", type: "Smokes", color: "RED", x: 0.228, y: 0.177, width: 0.018, height: 0.028, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-003", productId: "smokes", type: "Smokes", color: "RED", x: 0.206, y: 0.243, width: 0.018, height: 0.028, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-004", productId: "smokes", type: "Smokes", color: "RED", x: 0.090, y: 0.320, width: 0.018, height: 0.028, room: "CLASSROOM 302", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-005", productId: "smokes", type: "Smokes", color: "RED", x: 0.206, y: 0.331, width: 0.018, height: 0.028, room: "CLASSROOM 302", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-006", productId: "smokes", type: "Smokes", color: "RED", x: 0.350, y: 0.188, width: 0.018, height: 0.028, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-007", productId: "smokes", type: "Smokes", color: "RED", x: 0.469, y: 0.177, width: 0.018, height: 0.028, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-008", productId: "smokes", type: "Smokes", color: "RED", x: 0.533, y: 0.194, width: 0.018, height: 0.028, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-009", productId: "smokes", type: "Smokes", color: "RED", x: 0.320, y: 0.330, width: 0.018, height: 0.028, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-010", productId: "smokes", type: "Smokes", color: "RED", x: 0.406, y: 0.330, width: 0.018, height: 0.028, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-011", productId: "smokes", type: "Smokes", color: "RED", x: 0.486, y: 0.330, width: 0.018, height: 0.028, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-012", productId: "smokes", type: "Smokes", color: "RED", x: 0.320, y: 0.468, width: 0.018, height: 0.028, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-013", productId: "smokes", type: "Smokes", color: "RED", x: 0.486, y: 0.467, width: 0.018, height: 0.028, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-014", productId: "smokes", type: "Smokes", color: "RED", x: 0.600, y: 0.465, width: 0.018, height: 0.028, room: "ELEC. 309", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-015", productId: "smokes", type: "Smokes", color: "RED", x: 0.593, y: 0.650, width: 0.018, height: 0.028, room: "CONFERENCE 312", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-016", productId: "smokes", type: "Smokes", color: "RED", x: 0.164, y: 0.812, width: 0.018, height: 0.028, room: "SOUTHWEST ROOM", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-017", productId: "smokes", type: "Smokes", color: "RED", x: 0.285, y: 0.789, width: 0.018, height: 0.028, room: "OFFICE 313", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-018", productId: "smokes", type: "Smokes", color: "RED", x: 0.402, y: 0.789, width: 0.018, height: 0.028, room: "OFFICE 314", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-019", productId: "smokes", type: "Smokes", color: "RED", x: 0.596, y: 0.764, width: 0.018, height: 0.028, room: "BREAK ROOM 315", drawingReference: "FA-1.1" },
        { id: "ex003-heat-001", productId: "heat-detectors", type: "Heat Detectors", color: "LIGHT BLUE", x: 0.647, y: 0.359, width: 0.026, height: 0.039, room: "MECHANICAL 308", drawingReference: "FA-1.1" },
        { id: "ex003-ror-heat-001", productId: "ror-heats", type: "R of R Heats", color: "LIGHT BLUE", x: 0.409, y: 0.230, width: 0.026, height: 0.039, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-test-001", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.262, y: 0.590, width: 0.024, height: 0.032, room: "CORRIDOR 311", drawingReference: "FA-1.1" },
        { id: "ex003-hs-001", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.238, y: 0.130, width: 0.022, height: 0.031, room: "CLASSROOM 301 / NORTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-002", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.524, y: 0.129, width: 0.022, height: 0.031, room: "LAB 305 / NORTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-003", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.522, y: 0.584, width: 0.022, height: 0.031, room: "CORRIDOR 311", drawingReference: "FA-1.1" },
        { id: "ex003-hs-004", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.679, y: 0.626, width: 0.022, height: 0.031, room: "CONFERENCE 312", drawingReference: "FA-1.1" },
        { id: "ex003-hs-005", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.675, y: 0.173, width: 0.022, height: 0.031, room: "STORAGE 306 / EAST WALL", drawingReference: "FA-1.1" },
        { id: "ex003-pull-001", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.141, y: 0.669, width: 0.021, height: 0.031, room: "STAIR A", drawingReference: "FA-1.1" },
        { id: "ex003-pull-002", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.210, y: 0.844, width: 0.021, height: 0.031, room: "SOUTHWEST ROOM / SOUTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-pull-003", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.684, y: 0.784, width: 0.021, height: 0.031, room: "STAIR B", drawingReference: "FA-1.1" },
        { id: "ex003-wf-001", productId: "waterflow", type: "Waterflow", color: "PINK", x: 0.355, y: 0.909, width: 0.023, height: 0.035, room: "SOUTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-dh-001", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.208, y: 0.530, width: 0.022, height: 0.033, room: "WOMEN 304", drawingReference: "FA-1.1" },
        { id: "ex003-dh-002", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.372, y: 0.846, width: 0.022, height: 0.033, room: "OFFICE 314 / SOUTH WALL", drawingReference: "FA-1.1" }
    ],
    expectedQuantities: {
        FACP: 1,
        FAA: 1,
        Smokes: 16,
        "Heat Detectors": 1,
        "R of R Heats": 1,
        "Test Stations": 1,
        "Duct Smokes": 0,
        "Wall Horn/Strobes": 5,
        "Wall Speaker/Strobes": 0,
        Pulls: 3,
        "CR's": 0,
        Waterflow: 1,
        "Door Holders": 2,
        Tamper: 0
    },
    existingDevices: [],
    excludedDevices: [],
    specialInstructions: ["The new source PNG is authoritative. Smoke is the circle containing S; Heat is the diamond containing H; Rate-of-Rise Heat is the diamond containing R."]
};
