window.takeoffExercise003 = {
    exerciseId: "takeoff-practice-003",
    title: "Takeoff Practice 003",
    status: "APPROVED DRAWING",
    drawing: {
        asset: "../../Takeoff Drawings/97b81900-4fe0-4767-befe-a26e76618bee.png",
        sourceDocument: "97b81900-4fe0-4767-befe-a26e76618bee.png",
        drawingTitle: "FIRE ALARM PLAN - LEVEL 1",
        drawingNumber: "FA-1.1",
        project: "BAN-KOE ACADEMY - LEVEL 3",
        pages: 1
    },
    key: [
        { symbol: "FACP", description: "Fire Alarm Control Panel", color: "DARK BLUE" },
        { symbol: "FA", description: "Fire Alarm Annunciator", color: "DARK BLUE" },
        { symbol: "S", description: "Smoke Detector", color: "RED" },
        { symbol: "H", description: "Heat Detector (Fixed Temperature)", color: "LIGHT BLUE" },
        { symbol: "R", description: "Rate-of-Rise Heat Detector (Thermal)", color: "LIGHT BLUE" },
        { symbol: "TS", description: "Test Station", color: "ORANGE" },
        { symbol: "D", description: "Duct Smoke Detector", color: "ORANGE" },
        { symbol: "HS", description: "Wall Horn / Strobe", color: "YELLOW" },
        { symbol: "SS", description: "Wall Speaker / Strobe", color: "YELLOW" },
        { symbol: "P", description: "Manual Pull Station", color: "GREEN" },
        { symbol: "CR", description: "Control Relay", color: "PINK" },
        { symbol: "WF", description: "Waterflow Switch", color: "PINK" },
        { symbol: "DH", description: "Door Holder", color: "PINK" },
        { symbol: "T", description: "Tamper Switch", color: "PINK" }
    ],
    notes: [
        "Install devices per NFPA 72.",
        "Verify all device locations with architectural drawings.",
        "Mount devices per manufacturer recommendations.",
        "Coordinate with all trades.",
        "This is a training exercise only. Device quantities and locations are used for instructional purposes."
    ],
    products: [
        { id: "facp", whatIsIt: "FACP", color: "DARK BLUE" },
        { id: "faa", whatIsIt: "FAA", color: "DARK BLUE" },
        { id: "smokes", whatIsIt: "Smokes", color: "RED" },
        { id: "heat-detectors", whatIsIt: "Heat Detectors", color: "LIGHT BLUE" },
        { id: "ror-heats", whatIsIt: "R of R Heats", color: "LIGHT BLUE" },
        { id: "test-stations", whatIsIt: "Test Stations", color: "ORANGE" },
        { id: "duct-smokes", whatIsIt: "Duct Smokes", color: "ORANGE" },
        { id: "wall-horn-strobes", whatIsIt: "Wall Horn/Strobes", color: "YELLOW" },
        { id: "wall-speaker-strobes", whatIsIt: "Wall Speaker/Strobes", color: "YELLOW" },
        { id: "pulls", whatIsIt: "Pulls", color: "GREEN" },
        { id: "crs", whatIsIt: "CR's", color: "PINK" },
        { id: "waterflow", whatIsIt: "Waterflow", color: "PINK" },
        { id: "door-holders", whatIsIt: "Door Holders", color: "PINK" },
        { id: "tamper", whatIsIt: "Tamper", color: "PINK" }
    ],
    symbols: [],
    partNumbers: [],
    colors: [],
    locations: [
        { id: "ex003-facp-001", productId: "facp", type: "FACP", color: "DARK BLUE", x: 0.029, y: 0.561, width: 0.035, height: 0.032, room: "FIRE ALARM CONTROL PANEL", drawingReference: "FA-1.1" },
        { id: "ex003-faa-001", productId: "faa", type: "FAA", color: "DARK BLUE", x: 0.029, y: 0.417, width: 0.029, height: 0.031, room: "FIRE ALARM ANNUNCIATOR", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-001", productId: "smokes", type: "Smokes", color: "RED", x: 0.09, y: 0.16, width: 0.018, height: 0.029, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-002", productId: "smokes", type: "Smokes", color: "RED", x: 0.229, y: 0.177, width: 0.018, height: 0.029, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-003", productId: "smokes", type: "Smokes", color: "RED", x: 0.207, y: 0.241, width: 0.018, height: 0.029, room: "CLASSROOM 301", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-004", productId: "smokes", type: "Smokes", color: "RED", x: 0.349, y: 0.188, width: 0.018, height: 0.029, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-005", productId: "smokes", type: "Smokes", color: "RED", x: 0.469, y: 0.177, width: 0.018, height: 0.029, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-006", productId: "smokes", type: "Smokes", color: "RED", x: 0.533, y: 0.194, width: 0.018, height: 0.029, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-007", productId: "smokes", type: "Smokes", color: "RED", x: 0.275, y: 0.314, width: 0.018, height: 0.029, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-008", productId: "smokes", type: "Smokes", color: "RED", x: 0.471, y: 0.313, width: 0.018, height: 0.029, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-009", productId: "smokes", type: "Smokes", color: "RED", x: 0.598, y: 0.313, width: 0.018, height: 0.029, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-010", productId: "smokes", type: "Smokes", color: "RED", x: 0.68, y: 0.313, width: 0.018, height: 0.029, room: "OFFICE 308", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-011", productId: "smokes", type: "Smokes", color: "RED", x: 0.109, y: 0.361, width: 0.018, height: 0.029, room: "CONSULT 309", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-012", productId: "smokes", type: "Smokes", color: "RED", x: 0.314, y: 0.411, width: 0.018, height: 0.029, room: "NURSE STATION 310", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-013", productId: "smokes", type: "Smokes", color: "RED", x: 0.482, y: 0.411, width: 0.018, height: 0.029, room: "LAB 311", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-014", productId: "smokes", type: "Smokes", color: "RED", x: 0.702, y: 0.391, width: 0.018, height: 0.029, room: "ELECTRICAL 309", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-015", productId: "smokes", type: "Smokes", color: "RED", x: 0.125, y: 0.505, width: 0.018, height: 0.029, room: "WAITING 314", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-016", productId: "smokes", type: "Smokes", color: "RED", x: 0.322, y: 0.56, width: 0.018, height: 0.029, room: "OFFICE 313", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-017", productId: "smokes", type: "Smokes", color: "RED", x: 0.474, y: 0.56, width: 0.018, height: 0.029, room: "OFFICE 314", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-018", productId: "smokes", type: "Smokes", color: "RED", x: 0.596, y: 0.605, width: 0.018, height: 0.029, room: "BREAK ROOM 315", drawingReference: "FA-1.1" },
        { id: "ex003-smoke-019", productId: "smokes", type: "Smokes", color: "RED", x: 0.704, y: 0.51, width: 0.018, height: 0.029, room: "CONFERENCE 312", drawingReference: "FA-1.1" },
        { id: "ex003-heat-001", productId: "heat-detectors", type: "Heat Detectors", color: "LIGHT BLUE", x: 0.648, y: 0.36, width: 0.025, height: 0.035, room: "MECHANICAL 308", drawingReference: "FA-1.1" },
        { id: "ex003-ror-heat-001", productId: "ror-heats", type: "R of R Heats", color: "LIGHT BLUE", x: 0.409, y: 0.23, width: 0.029, height: 0.035, room: "LAB 305", drawingReference: "FA-1.1" },
        { id: "ex003-test-001", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.248, y: 0.323, width: 0.022, height: 0.032, room: "OPEN AREA 307", drawingReference: "FA-1.1" },
        { id: "ex003-duct-001", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.549, y: 0.32, width: 0.024, height: 0.032, room: "OPEN AREA 307 / RETURN AIR", drawingReference: "FA-1.1" },
        { id: "ex003-duct-002", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.091, y: 0.896, width: 0.024, height: 0.032, room: "LOWER PLAN / RETURN AIR", drawingReference: "FA-1.1" },
        { id: "ex003-hs-001", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.237, y: 0.128, width: 0.025, height: 0.032, room: "CLASSROOM 301 / NORTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-002", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.524, y: 0.126, width: 0.025, height: 0.032, room: "LAB 305 / NORTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-hs-003", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.512, y: 0.583, width: 0.025, height: 0.032, room: "CORRIDOR 311", drawingReference: "FA-1.1" },
        { id: "ex003-hs-004", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.682, y: 0.681, width: 0.025, height: 0.032, room: "CONFERENCE 312", drawingReference: "FA-1.1" },
        { id: "ex003-hs-005", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.682, y: 0.744, width: 0.025, height: 0.032, room: "CONFERENCE 312", drawingReference: "FA-1.1" },
        { id: "ex003-pull-001", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.135, y: 0.689, width: 0.025, height: 0.032, room: "STAIR A", drawingReference: "FA-1.1" },
        { id: "ex003-pull-002", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.223, y: 0.842, width: 0.025, height: 0.032, room: "STAIR A", drawingReference: "FA-1.1" },
        { id: "ex003-pull-003", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.677, y: 0.781, width: 0.025, height: 0.032, room: "STAIR B", drawingReference: "FA-1.1" },
        { id: "ex003-wf-001", productId: "waterflow", type: "Waterflow", color: "PINK", x: 0.354, y: 0.906, width: 0.028, height: 0.032, room: "SOUTH WALL", drawingReference: "FA-1.1" },
        { id: "ex003-dh-001", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.203, y: 0.506, width: 0.025, height: 0.032, room: "WOMEN 304", drawingReference: "FA-1.1" }
    ],
    expectedQuantities: {
        FACP: 1,
        FAA: 1,
        Smokes: 19,
        "Heat Detectors": 1,
        "R of R Heats": 1,
        "Test Stations": 1,
        "Duct Smokes": 2,
        "Wall Horn/Strobes": 5,
        "Wall Speaker/Strobes": 0,
        Pulls: 3,
        "CR's": 0,
        Waterflow: 1,
        "Door Holders": 1,
        Tamper: 0
    },
    existingDevices: [],
    excludedDevices: [],
    specialInstructions: ["The new source PNG is authoritative. Smoke is the circle containing S; Heat is the diamond containing H; Rate-of-Rise Heat is the diamond containing R."]
};
