const takeoffExercise002 = {
    exerciseId: "takeoff-practice-002",
    title: "Takeoff Practice 002",
    status: "APPROVED DRAWING - ANSWER DATA PENDING",
    drawing: {
        asset: "../../Takeoff Drawings/ChatGPT Image Aug 24, 2026, 02_21_04 PM.png",
        sourceDocument: "ChatGPT Image Aug 24, 2026, 02_21_04 PM.png",
        drawingTitle: "FIRE ALARM PLAN - FIRST FLOOR",
        drawingNumber: "FA-101",
        project: "RIVERDALE OFFICE BUILDING",
        pages: 1
    },
    key: [
        { symbol: "FACP", description: "Fire Alarm Control Panel", color: "DARK BLUE" },
        { symbol: "Smoke Detector", description: "Smoke Detector", color: "RED" },
        { symbol: "Heat Detector (Rate-of-Rise)", description: "Heat Detector (Rate-of-Rise)", color: "LIGHT BLUE" },
        { symbol: "Heat Detector (Fixed Temp)", description: "Heat Detector (Fixed Temp)", color: "LIGHT BLUE" },
        { symbol: "Wall Strobe", description: "Wall Strobe", color: "ORANGE" },
        { symbol: "Wall Horn/Strobe", description: "Wall Horn/Strobe", color: "YELLOW" },
        { symbol: "Wall Speaker/Strobe", description: "Wall Speaker/Strobe", color: "YELLOW" },
        { symbol: "Pull Station", description: "Pull Station", color: "GREEN" },
        { symbol: "Control Relay / Monitor Module", description: "Control Relay / Monitor Module", color: "PINK" },
        { symbol: "Test Station", description: "Test Station", color: "ORANGE" },
        { symbol: "Duct Smoke Detector", description: "Duct Smoke Detector", color: "ORANGE" },
        { symbol: "Waterflow Switch", description: "Waterflow Switch", color: "PINK" },
        { symbol: "Door Holder", description: "Door Holder", color: "PINK" },
        { symbol: "Tamper Switch", description: "Tamper Switch", color: "PINK" },
        { symbol: "Fire Alarm Annunciator", description: "Fire Alarm Annunciator", color: "DARK BLUE" }
    ],
    notes: [
        "ALL DEVICES AND WIRING SHALL BE INSTALLED IN ACCORDANCE WITH NFPA 72, 2019 EDITION AND ALL APPLICABLE CODES.",
        "MOUNT SMOKE DETECTORS A MINIMUM OF 4' FROM WALLS UNLESS NOTED OTHERWISE.",
        "MOUNT HEAT DETECTORS PER MANUFACTURER'S RECOMMENDATIONS.",
        "MANUAL PULL STATIONS SHALL BE MOUNTED 48\" AFF TO TOP OF DEVICE.",
        "STROBES SHALL BE MOUNTED 80\" AFF TO TOP OF DEVICE UNLESS NOTED OTHERWISE.",
        "HORN/STROBES SHALL BE MOUNTED 90\" AFF TO TOP OF DEVICE UNLESS NOTED OTHERWISE.",
        "DUCT SMOKE DETECTORS SHALL BE INSTALLED PER NFPA 90A AND MANUFACTURER'S REQUIREMENTS.",
        "WATERFLOW SWITCH SHALL BE INSTALLED ON THE FIRE PROTECTION MAIN RISER.",
        "ALL CIRCUITS ARE CLASS B UNLESS NOTED OTHERWISE."
    ],
    products: [
        { id: "facp", whatIsIt: "FACP", color: "DARK BLUE" },
        { id: "faa", whatIsIt: "FAA", color: "DARK BLUE" },
        { id: "smokes", whatIsIt: "Smokes", color: "RED" },
        { id: "ror-heats", whatIsIt: "R of R Heats", color: "LIGHT BLUE" },
        { id: "fixed-heats", whatIsIt: "Fixed Heats", color: "LIGHT BLUE" },
        { id: "heat-detectors", whatIsIt: "Heat Detectors", color: "LIGHT BLUE" },
        { id: "duct-smokes", whatIsIt: "Duct Smokes", color: "ORANGE" },
        { id: "test-stations", whatIsIt: "Test Stations", color: "ORANGE" },
        { id: "wall-strobes", whatIsIt: "Wall Strobes", color: "ORANGE" },
        { id: "ceiling-strobes", whatIsIt: "Ceiling Strobes", color: "ORANGE" },
        { id: "wall-horn-strobes", whatIsIt: "Wall Horn/Strobes", color: "YELLOW" },
        { id: "wall-speaker-strobes", whatIsIt: "Wall Speaker/Strobes", color: "YELLOW" },
        { id: "ceiling-horn-strobes", whatIsIt: "Ceiling Horn/Strobes", color: "YELLOW" },
        { id: "ceiling-speaker-strobes", whatIsIt: "Ceiling Speaker/Strobes", color: "YELLOW" },
        { id: "weatherproof-devices", whatIsIt: "Weatherproof Devices", color: "YELLOW" },
        { id: "pulls", whatIsIt: "Pulls", color: "GREEN" },
        { id: "crs", whatIsIt: "CR's", color: "PINK" },
        { id: "waterflow", whatIsIt: "Waterflow", color: "PINK" },
        { id: "door-holders", whatIsIt: "Door Holders", color: "PINK" },
        { id: "tamper", whatIsIt: "Tamper", color: "PINK" }
    ],
    symbols: [],
    partNumbers: [],
    colors: [],
    locations: [
        { id: "facp-001", productId: "facp", type: "FACP", color: "DARK BLUE", x: 0.365, y: 0.741, width: 0.045, height: 0.035, room: "ELEC. 109", drawingReference: "FA-101" },
        { id: "faa-001", productId: "faa", type: "FAA", color: "DARK BLUE", x: 0.66, y: 0.743, width: 0.038, height: 0.028, room: "LOBBY 100", drawingReference: "FA-101" },
        { id: "smoke-001", productId: "smokes", type: "Smokes", color: "RED", x: 0.409, y: 0.189, width: 0.02, height: 0.02, room: "OPEN OFFICE 101", drawingReference: "FA-101" },
        { id: "smoke-002", productId: "smokes", type: "Smokes", color: "RED", x: 0.403, y: 0.335, width: 0.02, height: 0.02, room: "OPEN OFFICE 101", drawingReference: "FA-101" },
        { id: "smoke-003", productId: "smokes", type: "Smokes", color: "RED", x: 0.615, y: 0.27, width: 0.02, height: 0.02, room: "CONFERENCE 102", drawingReference: "FA-101" },
        { id: "smoke-004", productId: "smokes", type: "Smokes", color: "RED", x: 0.86, y: 0.189, width: 0.02, height: 0.02, room: "OPEN OFFICE 103", drawingReference: "FA-101" },
        { id: "smoke-005", productId: "smokes", type: "Smokes", color: "RED", x: 0.837, y: 0.335, width: 0.02, height: 0.02, room: "OPEN OFFICE 103", drawingReference: "FA-101" },
        { id: "smoke-006", productId: "smokes", type: "Smokes", color: "RED", x: 0.366, y: 0.55, width: 0.02, height: 0.02, room: "OFFICE 104", drawingReference: "FA-101" },
        { id: "smoke-007", productId: "smokes", type: "Smokes", color: "RED", x: 0.574, y: 0.547, width: 0.02, height: 0.02, room: "BREAK ROOM 105", drawingReference: "FA-101" },
        { id: "smoke-008", productId: "smokes", type: "Smokes", color: "RED", x: 0.718, y: 0.737, width: 0.02, height: 0.02, room: "LOBBY 100", drawingReference: "FA-101" },
        { id: "smoke-009", productId: "smokes", type: "Smokes", color: "RED", x: 0.87, y: 0.737, width: 0.02, height: 0.02, room: "SERVER 110", drawingReference: "FA-101" },
        { id: "smoke-010", productId: "smokes", type: "Smokes", color: "RED", x: 0.768, y: 0.231, width: 0.02, height: 0.02, room: "OPEN OFFICE 103", drawingReference: "FA-101" },
        { id: "smoke-011", productId: "smokes", type: "Smokes", color: "RED", x: 0.889, y: 0.563, width: 0.02, height: 0.02, room: "OFFICE 108", drawingReference: "FA-101" },
        { id: "smoke-012", productId: "smokes", type: "Smokes", color: "RED", x: 0.518, y: 0.736, width: 0.02, height: 0.02, room: "LOBBY 100", drawingReference: "FA-101" },
        { id: "ror-heat-001", productId: "ror-heats", type: "R of R Heats", color: "LIGHT BLUE", x: 0.463, y: 0.234, width: 0.02, height: 0.02, room: "OPEN OFFICE 101", drawingReference: "FA-101" },
        { id: "ror-heat-002", productId: "heat-detectors", type: "Heat Detectors", color: "LIGHT BLUE", x: 0.859, y: 0.234, width: 0.02, height: 0.02, room: "OPEN OFFICE 103", drawingReference: "FA-101" },
        { id: "ror-heat-003", productId: "heat-detectors", type: "Heat Detectors", color: "LIGHT BLUE", x: 0.718, y: 0.688, width: 0.02, height: 0.02, room: "LOBBY 100", drawingReference: "FA-101" },
        { id: "test-001", productId: "test-stations", type: "Test Stations", color: "ORANGE", x: 0.547, y: 0.188, width: 0.025, height: 0.025, room: "CONFERENCE 102", drawingReference: "FA-101" },
        { id: "duct-001", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.964, y: 0.272, width: 0.025, height: 0.025, room: "OPEN OFFICE 103 / DUCT", drawingReference: "FA-101" },
        { id: "duct-002", productId: "duct-smokes", type: "Duct Smokes", color: "ORANGE", x: 0.964, y: 0.519, width: 0.025, height: 0.025, room: "OFFICE 108 / DUCT", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-001", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.466, y: 0.173, width: 0.018, height: 0.018, room: "OPEN OFFICE 101 / NORTH WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-002", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.63, y: 0.173, width: 0.018, height: 0.018, room: "CONFERENCE 102 / NORTH WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-003", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.771, y: 0.173, width: 0.018, height: 0.018, room: "OPEN OFFICE 103 / NORTH WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-004", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.331, y: 0.330, width: 0.018, height: 0.018, room: "OPEN OFFICE 101 / WEST WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-005", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.94, y: 0.331, width: 0.018, height: 0.018, room: "OPEN OFFICE 103 / EAST WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-006", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.331, y: 0.547, width: 0.018, height: 0.018, room: "OFFICE 104 / WEST WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-007", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.645, y: 0.535, width: 0.018, height: 0.018, room: "BREAK ROOM 105 / EAST WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-008", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.938, y: 0.610, width: 0.018, height: 0.018, room: "OFFICE 108 / EAST WALL", drawingReference: "FA-101" },
        { id: "wall-speaker-strobe-009", productId: "wall-speaker-strobes", type: "Wall Speaker/Strobes", color: "YELLOW", x: 0.331, y: 0.775, width: 0.018, height: 0.018, room: "ELEC. 109 / WEST WALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-001", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.522, y: 0.296, width: 0.025, height: 0.025, room: "CONFERENCE 102 / WEST WALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-002", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.695, y: 0.296, width: 0.025, height: 0.025, room: "CONFERENCE 102 / EAST WALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-003", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.563, y: 0.448, width: 0.025, height: 0.025, room: "BREAK ROOM 105 / NORTH WALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-004", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.773, y: 0.448, width: 0.025, height: 0.025, room: "MEN/WOMEN 106/107 / NORTH WALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-005", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.462, y: 0.616, width: 0.025, height: 0.025, room: "OFFICE 104 / HALL", drawingReference: "FA-101" },
        { id: "wall-horn-strobe-006", productId: "wall-horn-strobes", type: "Wall Horn/Strobes", color: "YELLOW", x: 0.837, y: 0.616, width: 0.025, height: 0.025, room: "OFFICE 108 / HALL", drawingReference: "FA-101" },
        { id: "pull-001", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.326, y: 0.393, width: 0.025, height: 0.025, room: "HALL / WEST", drawingReference: "FA-101" },
        { id: "pull-002", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.92, y: 0.393, width: 0.025, height: 0.025, room: "HALL / EAST", drawingReference: "FA-101" },
        { id: "pull-003", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.48, y: 0.529, width: 0.025, height: 0.025, room: "HALL / BREAK ROOM", drawingReference: "FA-101" },
        { id: "pull-004", productId: "pulls", type: "Pulls", color: "GREEN", x: 0.52, y: 0.794, width: 0.025, height: 0.025, room: "LOBBY 100 / ENTRY", drawingReference: "FA-101" },
        { id: "cr-001", productId: "crs", type: "CR's", color: "PINK", x: 0.335, y: 0.188, width: 0.025, height: 0.025, room: "OPEN OFFICE 101 / WEST", drawingReference: "FA-101" },
        { id: "cr-002", productId: "crs", type: "CR's", color: "PINK", x: 0.931, y: 0.188, width: 0.025, height: 0.025, room: "OPEN OFFICE 103 / EAST", drawingReference: "FA-101" },
        { id: "cr-003", productId: "crs", type: "CR's", color: "PINK", x: 0.417, y: 0.688, width: 0.025, height: 0.025, room: "ELEC. 109", drawingReference: "FA-101" },
        { id: "waterflow-001", productId: "waterflow", type: "Waterflow", color: "PINK", x: 0.385, y: 0.853, width: 0.025, height: 0.025, room: "FIRE RISER / ELEC. 109", drawingReference: "FA-101" },
        { id: "door-holder-001", productId: "door-holders", type: "Door Holders", color: "PINK", x: 0.566, y: 0.795, width: 0.025, height: 0.025, room: "LOBBY 100 / ENTRY", drawingReference: "FA-101" },
        { id: "tamper-001", productId: "tamper", type: "Tamper", color: "PINK", x: 0.791, y: 0.728, width: 0.025, height: 0.025, room: "SERVER 110", drawingReference: "FA-101" }
    ],
    expectedQuantities: {
        FACP: 1,
        FAA: 1,
        Smokes: 12,
        "R of R Heats": 1,
        "Heat Detectors": 2,
        "Test Stations": 1,
        "Duct Smokes": 2,
        "Wall Speaker/Strobes": 9,
        "Wall Horn/Strobes": 6,
        Pulls: 4,
        "CR's": 3,
        Waterflow: 1,
        "Door Holders": 1,
        Tamper: 1
    },
    existingDevices: [],
    excludedDevices: [],
    specialInstructions: ["Use the key and notes shown on the drawing. This answer data was generated from the QA-approved Exercise 002 device mapping."]
};
