const ACCESS_PROGRESS_KEY = "bkaAccessControlTraining";

const accessModules = [
    { label: "Basics", chip: "System Flow", title: "Understand the access-control decision path.", objective: "Recognize the parts of a door system and how a credential becomes a lock action." },
    { label: "Controllers", chip: "Aero + VertX", title: "Separate current Aero hardware from legacy VertX hardware.", objective: "See X1100 as the brain, then match X100, X200, and X300 to their jobs." },
    { label: "Locks", chip: "Lock Recognition", title: "Match the lock type to the door and application.", objective: "Recognize HES 1006, HES 9600, maglocks, and the fail-safe/fail-secure decision." },
    { label: "Exit Devices", chip: "QEL + Transfer", title: "Trace power and control through an electrified exit device.", objective: "Connect 98/99, QEL, power supplies, and PTH/EPT into one complete opening." },
    { label: "Electrical", chip: "Voltage + Relays", title: "Use electrical language accurately while estimating.", objective: "Apply volts, amps, watts, relay outputs, and COM without relying on unsafe assumptions." },
    { label: "Estimating", chip: "Complete Door", title: "Turn a door scenario into a quote checklist.", objective: "Ask the questions that reveal hardware, power, wiring, compatibility, and reuse requirements." },
    { label: "Quiz", chip: "Access Control Quiz", title: "Prove recognition, function, application, and estimating judgment.", objective: "Move from seeing a part number to knowing what it works with and what else may be required." }
];

const productCard = (part, product, use, details, priority = "") => `<article class="product-card ${priority}"><span class="product-label">${priority === "must" ? "Must know" : priority === "should" ? "Should know" : "Product recognition"}</span><h3>${part}</h3><p><strong>Product:</strong> ${product}</p><p><strong>Use:</strong> ${use}</p><p>${details}</p></article>`;

const accessContent = [
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 1</p><h2>Access Control Basics</h2></div><span class="badge">Foundation</span></div><p>Access control decides whether a person or credential should be allowed through an opening, then controls and monitors the door hardware.</p><div class="access-flow"><div class="flow-node">Reader<small>Identifies the credential/user</small></div><div class="flow-arrow">→</div><div class="flow-node">Controller<small>The brain and decision maker</small></div><div class="flow-arrow">→</div><div class="flow-node">Relay<small>Switches the control function</small></div><div class="flow-arrow">→</div><div class="flow-node">Lock<small>Releases or remains locked</small></div></div><div class="info-grid"><article class="info-card"><h3>Door status</h3><p>Door contacts report whether an opening is open or closed. If a door stays open longer than its programmed time, the system can create a <strong>Door Ajar</strong> condition or alarm.</p></article><article class="info-card"><h3>REX</h3><p><strong>REX = Request to Exit.</strong> A REX device tells the system that someone is intentionally exiting. Examples include push buttons, motion/request-to-exit sensors, and other exit devices selected for the application.</p></article><article class="info-card"><h3>Credentials + network</h3><p>Cards and other credentials are presented to readers. Controllers communicate with the access-control platform over the network, depending on the system architecture.</p></article><article class="info-card"><h3>Other field pieces</h3><p>Door contacts, REX devices, HID boxes/enclosures, readers, controllers, relays, locking hardware, power supplies, and wiring all belong to the complete opening conversation.</p></article></div></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 2</p><h2>Controllers &amp; Modules</h2></div><span class="badge">Current vs legacy</span></div><div class="callout"><strong>Memory trick:</strong> X1100 = Brain · X100 = Readers / Doors · X200 = Inputs · X300 = Outputs</div><h3>Current — HID Aero</h3><div class="info-grid">${productCard("X1100", "HID Aero intelligent controller", "Controller / brain", "Supports up to two local access points, up to four OSDP readers or two Wiegand readers locally, seven inputs, and four Form-C relays. It accepts 12–24 VDC input, can expand to as many as 64 readers and 64 access points, and can use X100, X200, X300 plus VertX V100, V200, and V300 modules.", "must")}${productCard("X100", "HID Aero reader/door interface", "Expansion interface", "Supports up to four readers, seven inputs, and four outputs.", "must")}${productCard("X200", "HID Aero input module", "Inputs", "Supports up to 16 general-purpose inputs.", "must")}${productCard("X300", "HID Aero output/relay module", "Outputs / relays", "Supports up to 12 general-purpose outputs.", "must")}</div><h3>Legacy / Existing-System Hardware — HID VertX</h3><p>VertX is not the primary current platform, but it matters on existing projects. The current X1100 is designed as a form-and-fit replacement for VertX controllers and can communicate with existing VertX V100, V200, and V300 modules.</p><div class="info-grid">${productCard("V1000", "VertX master controller", "Controller / brain", "Can support up to 64 readers with expansion.", "must")}${productCard("V100", "VertX door/reader interface", "Door and reader interface", "Legacy / existing-system hardware.", "must")}${productCard("V200", "VertX input module", "Inputs", "Teach this as 16 inputs, not 12.", "must")}${productCard("V300", "VertX relay/output module", "Relay / output", "Provides 12 Form-C relays.", "must")}</div></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 3</p><h2>Locking Hardware</h2></div><span class="badge">High-priority recognition</span></div><div class="info-grid">${productCard("HES 1006", "Electric strike", "Cylindrical / mortise locks", "Installed in the frame to electrically release the latch. It works with cylindrical locks, mortise locks, and mortise locks with deadbolts; accommodates up to a 1 inch deadbolt; uses 12/24 V; and has heavy-duty stainless-steel construction with multiple faceplate options.", "must")}${productCard("HES 9600", "Surface-mounted electric strike", "Rim exit devices", "Accommodates up to a 3/4 inch Pullman latch, uses 12/24 VDC, is field selectable fail-safe/fail-secure, can be used on metal or wood frames, is windstorm rated, and has latch-monitoring options.", "must")}</div><div class="memory">1006 → Cylindrical / Mortise Electric Strike &nbsp;&nbsp; | &nbsp;&nbsp; 9600 → Rim Exit Device</div><h3>Know the HES family</h3><div class="table-shell"><table class="family-table"><thead><tr><th>Family</th><th>General application association</th></tr></thead><tbody><tr><td>1006</td><td>Cylindrical / mortise</td></tr><tr><td>1500</td><td>Cylindrical / mortise</td></tr><tr><td>1600</td><td>Cylindrical / mortise / deadbolt applications</td></tr><tr><td>5000 / 5300</td><td>5300: compact / fire-rated applications</td></tr><tr><td>9400 / 9500</td><td>9400: low-profile Pullman latch; 9500: Pullman latch / fire-rated</td></tr><tr><td>9600 / 9700 / 9800</td><td>9600: Pullman latch / rim exit / windstorm; 9700: squarebolt / Pullman / rated; 9800: Adams Rite / rim exit</td></tr></tbody></table></div><div class="compare-grid"><article class="compare-card"><h3>Electric strike</h3><p>Releases the mechanical latch in the frame when access is authorized.</p></article><article class="compare-card"><h3>Maglock = magnetic lock</h3><p>Uses electromagnetic force to hold the door. It requires power to maintain the locking force; authorized access removes/releases that force.</p></article></div><div class="compare-grid"><article class="compare-card fail-safe"><h3>Fail-safe</h3><p><strong>Power failure → unlocked.</strong></p></article><article class="compare-card fail-secure"><h3>Fail-secure</h3><p><strong>Power failure → remains locked.</strong></p></article></div><div class="callout warning"><strong>There is no universally better choice.</strong> Select fail-safe or fail-secure based on the application, hardware, code, required means of egress, life-safety requirements, and project specifications.</div></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 4</p><h2>Exit Devices &amp; Door Hardware</h2></div><span class="badge">Power path</span></div><div class="info-grid">${productCard("Von Duprin 98/99", "Heavy-duty push-pad exit device", "Institutional exit openings", "A common institutional exit device used in schools, hospitals, government buildings, and similar applications. The 98 and 99 are related product families with different mechanism-case designs.", "must")}${productCard("QEL", "Quiet Electric Latch Retraction", "Electrified exit-device control", "Electrically retracts the latch so an access-control system can momentarily release a compatible exit device. It reduces operating noise, is available across multiple Von Duprin families, and can retrofit compatible existing devices.", "must")}${productCard("PTH / EPT", "Power transfer", "Moving doors", "PTH means Power Transfer Hinge. EPT products such as EPT-2 and EPT-10 transfer power from the stationary frame into the moving door.", "must")}${productCard("Other hardware", "Electrified hardware family", "Complete openings", "Recognize rim exit devices, crash bars, electrified lever sets, electrified locks, mullions, wireless locks, and pneumatic push buttons. Families such as 33A/35A, 22, 94/95, 75/78, and 88 are reference knowledge rather than a configuration memorization test.", "should")}</div><div class="callout"><strong>QEL electrical information:</strong> 24 VDC · 1.0 A inrush · 0.14 A holding.</div><h3>How the parts work together</h3><div class="access-flow"><div class="flow-node">Credential reader</div><div class="flow-arrow">↓</div><div class="flow-node">HID controller</div><div class="flow-arrow">↓</div><div class="flow-node">Access-control relay</div><div class="flow-arrow">↓</div><div class="flow-node">Power supply</div></div><p class="memory">Power supply → Frame → Power transfer → Door hardware → Von Duprin QEL → Exit-device latch retracts</p><p>QEL does not automatically include the power transfer or power supply. Treat them as separate estimating considerations, along with wiring and the controller/relay path.</p></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 5</p><h2>Electrical &amp; Relays</h2></div><span class="badge">Estimating basics</span></div><div class="info-grid"><article class="info-card"><h3>Voltage</h3><p><strong>Volts = electrical pressure.</strong> For access-control hardware, 12 VDC and 24 VDC are especially important values to verify.</p></article><article class="info-card"><h3>Amperage</h3><p><strong>Amps = amount of electrical current.</strong> Use the manufacturer load and the complete system design.</p></article><article class="info-card"><h3>Wattage</h3><p><strong>Watts = electrical power.</strong> Watts = Volts × Amps. Example: 24 V × 1 A = 24 W.</p></article><article class="info-card"><h3>AC vs DC</h3><p>AC is Alternating Current. DC is Direct Current. Do not assume every access-control device uses DC; verify the manufacturer's requirements.</p></article></div><div class="info-grid"><article class="info-card"><h3>Relay</h3><p>A relay is an electrically controlled switch. Relays can control door locks, HVAC, alarms, and other electrical equipment.</p></article>${productCard("ACM8", "8-relay access-control module", "Relay outputs", "Provides eight relays with individual fusing/protection. Estimating memory: 1 ACM8 = 8 relay outputs; 2 ACM8 = 16 relay outputs. It is one possible output solution, not an automatic requirement.", "must")}</div><div class="callout"><strong>COM = Common.</strong> COM does not always mean negative. In many DC circuits it may be connected to the negative/0 V side, but its actual electrical relationship depends on how the specific circuit is wired.</div></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 6</p><h2>New vs. Existing Projects</h2></div><span class="badge">Sales support mindset</span></div><div class="compare-grid"><article class="compare-card"><h3>New project</h3><ul><li>Number of doors and readers</li><li>Controller and input requirements</li><li>Relay/output requirements</li><li>Locking hardware and exit devices</li><li>Power supplies, voltage, current draw</li><li>Power transfer, wiring, door hardware, and accessories</li></ul><p class="memory">Ask: “What does this door need to function as an access-controlled opening?”</p></article><article class="compare-card"><h3>Existing project</h3><ul><li>Existing controller, readers, platform, and relay modules</li><li>Existing locks, door hardware, power supply, inputs, and wiring</li><li>Existing voltage and system condition</li><li>Compatibility and reuse opportunities</li></ul><p class="memory">Separate new hardware from replacement/upgrade hardware.</p></article></div><h3>Before You Quote an Access-Control Door</h3><div class="check-list">${["How many doors?", "What type of doors?", "What type of lock?", "What type of exit device?", "Is the hardware electrified?", "What voltage and current are required?", "What controller and reader are required?", "What inputs and relay/output are required?", "Is a power supply required?", "Is power transfer required?", "Is existing hardware being reused?", "Are additional accessories required?"].map((item, index) => `<label><input type="checkbox" data-quote-check="${index}"><span>${item}</span></label>`).join("")}</div><div class="scenario-card"><h3>Estimating principle</h3><p>See the complete door, not just the product. A part number should lead to its function, its application, the control path, power, transfer, wiring, and any additional components that may be required.</p></div></section>`,
    `<section class="access-step"><div class="section-heading compact"><div><p class="eyebrow">Module 7</p><h2>Access Control Quiz</h2></div><span class="badge">Five difficulty levels</span></div><p>Use the existing Ban-Koe quiz engine to practice recognition, function, application, system relationships, and estimating. Results are tracked independently as Access Control.</p><div class="info-grid"><article class="info-card"><h3>Level 1 — Recognition</h3><p>What is this part?</p></article><article class="info-card"><h3>Level 2 — Function</h3><p>What does this part do?</p></article><article class="info-card"><h3>Level 3 — Application</h3><p>Which product fits this situation?</p></article><article class="info-card"><h3>Level 4/5 — Relationships + estimating</h3><p>What else is required for the complete door?</p></article></div><div class="memory">See a part number → know what it is → know what it does → know what it works with → know what else may be required.</div><div class="module-actions"><span class="small-note">The quiz includes HID Aero/VertX, HES, Von Duprin, QEL, electrical, fail-state, and estimating scenarios.</span><a class="btn btn-primary" href="../../quiz/index.html?category=access-control">Open Access Control Quiz →</a></div></section>`
];

let currentModule = 0;
let progressState = loadAccessProgress();
const stepList = document.getElementById("accessStepList");
const main = document.getElementById("accessMain");

function loadAccessProgress() {
    try { return JSON.parse(localStorage.getItem(ACCESS_PROGRESS_KEY)) || { completed: [] }; } catch { return { completed: [] }; }
}
function saveAccessProgress() { localStorage.setItem(ACCESS_PROGRESS_KEY, JSON.stringify(progressState)); }
function renderShell() {
    stepList.innerHTML = accessModules.map((module, index) => `<button type="button" class="module-step-item ${index === currentModule ? "is-active" : ""} ${progressState.completed.includes(index) ? "is-complete" : ""}" data-access-step="${index}"><span class="module-step-icon">${progressState.completed.includes(index) ? "✓" : index === currentModule ? "●" : "○"}</span>${index + 1} ${module.label}</button>`).join("");
    stepList.querySelectorAll("[data-access-step]").forEach((button) => button.addEventListener("click", () => { currentModule = Number(button.dataset.accessStep); render(); }));
    const module = accessModules[currentModule];
    document.getElementById("accessObjectiveChip").textContent = module.chip;
    document.getElementById("accessObjectiveTitle").textContent = module.title;
    document.getElementById("accessObjectiveText").textContent = module.objective;
}
function render() {
    renderShell();
    main.innerHTML = `${accessContent[currentModule]}${currentModule < 6 ? `<div class="module-actions"><span class="small-note">Mark this lesson complete after reviewing the cards and examples.</span><button id="completeAccessLesson" class="btn btn-primary" type="button">${progressState.completed.includes(currentModule) ? "Lesson Complete ✓" : "Mark Lesson Complete"}</button></div>` : ""}`;
    const completeButton = document.getElementById("completeAccessLesson");
    if (completeButton) completeButton.addEventListener("click", () => { if (!progressState.completed.includes(currentModule)) progressState.completed.push(currentModule); saveAccessProgress(); render(); });
}

window.addEventListener("DOMContentLoaded", render);
